sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gugamm/frontend-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true gugamm/frontend-dev npm run test

