sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gugamm/frontend-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true gugamm/frontend-dev npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-490375428909'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
